version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting Docker daemon..."
      - sudo nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay &
      - timeout 15 sh -c "until docker info; do echo .; sleep 5; done"

  pre_build:
    commands:
      - echo "Installing React dependencies..."
      - npm install
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 425750453685.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=425750453685.dkr.ecr.ap-southeast-1.amazonaws.com/tenderboard-genai-stg-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building React production build..."
      - npm run build
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating imagedefinitions.json for ECS..."
      - printf '[{"name":"tenderboard-genai-stg-frontend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Updating ECS Service..."
      - aws ecs update-service --cluster tenderboard-genai-stg-ecs-app-services --service tenderboard-genai-stg-service-prmarshall --force-new-deployment --region ap-southeast-1

artifacts:
  files:
    - imagedefinitions.json
